# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
   vmImage: QG Build Servers
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment: 
      name: VMenv
      resourceType: virtualMachine
      resourceName: TestServer01 # only deploy to the VM resource named USHAN-PC
      #tags: "service"
    strategy:
            runOnce:
              deploy:
                steps:
                  - download: none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '9612dbff-498c-4266-9eb3-0ff777d5cbbc'

  # Web app name
  webAppName: 'ajaygoud558'

  # Environment name
  environmentName: 'ajaygoud558'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'


  